version: '2'
#Volume used by elasticsearch and db
volumes:
  esdata:
  redis:
  db:

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_test
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/run/mysqld
    ports:
      - "3307:3306"
  app:
    build: .
    command: bash -c "rm -f -- /chat_test/tmp/pids/server.pid && bundle install && bin/rails db:migrate RAILS_ENV=development && bin/rails runner 'Message.create_index!' && bundle exec rails s -p 3000 -b '0.0.0.0'"
#    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/chat_test"
    ports:
      - "3001:3000"
    depends_on:
      - db
      - elasticsearch
    links:
      - db
      - elasticsearch
    environment:
      DB_USER: root
      DB_NAME: chat_test
      DB_PASSWORD: password
      DB_HOST: db
      ELASTICSEARCH_HOST: elasticsearch
      REDIS_URL_SIDEKIQ: redis://redis:6379/1

  #Container for Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      -  esdata:/usr/share/elasticsearch/data
  kibana:
      #Match the version numbers of elasticsearch and kibana images
      image: docker.elastic.co/kibana/kibana:7.10.1
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  sidekiq:
    depends_on:
      - redis
      - db
    build: .
    command: bundle exec sidekiq
    volumes:
      - ".:/chat_test"
      - '/chat_test/tmp' # don't mount tmp directory
    environment:
      DB_USER: root
      DB_NAME: chat_test
      DB_PASSWORD: password
      DB_HOST: db
      ELASTICSEARCH_HOST: elasticsearch
      REDIS_URL_SIDEKIQ: redis://redis:6379/1
